// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQWroaKz6_i8HiQQzhWJvwMl0WGNBYe20',
    appId: '1:396250893016:web:c50f8534558ed97037a5ad',
    messagingSenderId: '396250893016',
    projectId: 'gestor-hospitalar-app-47cb9',
    authDomain: 'gestor-hospitalar-app-47cb9.firebaseapp.com',
    storageBucket: 'gestor-hospitalar-app-47cb9.firebasestorage.app',
    measurementId: 'G-B44F2XEKCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWEOjp-E2wQrD4sqKYIkTAcdXXR1MTlew',
    appId: '1:396250893016:android:35dd9ac5f9dc577837a5ad',
    messagingSenderId: '396250893016',
    projectId: 'gestor-hospitalar-app-47cb9',
    storageBucket: 'gestor-hospitalar-app-47cb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACWBIwXx3ceg2BogFEtJIP__wHSQ9HDvA',
    appId: '1:396250893016:ios:6777666960a1da2737a5ad',
    messagingSenderId: '396250893016',
    projectId: 'gestor-hospitalar-app-47cb9',
    storageBucket: 'gestor-hospitalar-app-47cb9.firebasestorage.app',
    iosBundleId: 'com.example.gestorHospitalarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACWBIwXx3ceg2BogFEtJIP__wHSQ9HDvA',
    appId: '1:396250893016:ios:6777666960a1da2737a5ad',
    messagingSenderId: '396250893016',
    projectId: 'gestor-hospitalar-app-47cb9',
    storageBucket: 'gestor-hospitalar-app-47cb9.firebasestorage.app',
    iosBundleId: 'com.example.gestorHospitalarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQWroaKz6_i8HiQQzhWJvwMl0WGNBYe20',
    appId: '1:396250893016:web:2522e93149a90be637a5ad',
    messagingSenderId: '396250893016',
    projectId: 'gestor-hospitalar-app-47cb9',
    authDomain: 'gestor-hospitalar-app-47cb9.firebaseapp.com',
    storageBucket: 'gestor-hospitalar-app-47cb9.firebasestorage.app',
    measurementId: 'G-ZF1DB4JWZG',
  );
}
